services:
  # ========================
  # PostgreSQL Database
  # ========================
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # ========================
  # FastAPI Backend
  # ========================
  fastapi:
    build: ./contracts-backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  # ========================
  # Nginx Proxy
  # ========================
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - app_network
    restart: always

# ========================
# Networks & Volumes
# ========================
networks:
  app_network:

volumes:
  postgres_data:
