services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    restart: always

  db_api:
    build: ./DB_server
    container_name: db_api
    ports:
      - "8001:80"  # ← ホスト側は8001番にすることでFastAPIの8000番と競合回避
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase

    
  fastapi:
    build: ./contracts-backend
    container_name: fastapi_app
    env_file:
      - ./contracts-backend/.env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
