version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 追加

  web:
    build: ./web
    ports:
      - "8000:80"  # ホストの8000番ポートをコンテナの80番ポートにマッピング
      - "50403:443"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase


volumes:
  postgres_data:
