name: Deploy to Sakura VPS

on:
  push:
    branches:
      - tyyti-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        echo "INFURA_URL=${{ secrets.INFURA_URL }}" >> ./contracts-backend/.env
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> ./contracts-backend/.env
        echo "CONTRACT_ADDRESS=${{ secrets.CONTRACT_ADDRESS }}" >> ./contracts-backend/.env
        echo "ADMIN_API_KEY=${{ secrets.ADMIN_API_KEY }}" >> ./contracts-backend/.env
        echo "API_SERVER_IP=${{ secrets.API_SERVER_IP }}" >> ./contracts-backend/.env

    # - name: Deploy with SSH
    #   uses: appleboy/ssh-action@v0.1.6
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USER }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     script: |
    #       cd ~/SocialTokenApp
    #       git pull origin tyyti-dev
    #       docker compose down
    #       docker compose up -d --build